import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link"
import LoginBtn from "@/component/LoginBtn"
import LogOutBtn from '@/component/LogOutBtn'
import { authOptions } from "@/pages/api/auth/[...nextauth].js"
import { getServerSession } from "next-auth";
import RegisterBtn from '@/component/register'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// 레이아웃

export default async function RootLayout({ children }) {
  let menuType = 0;
  let session = await getServerSession(authOptions)

  if(session){
    if(session.user.type == "customer"){
      menuType = 1
    }else if(session.user.type == "business"){
      menuType = 2
    }
  }

  const menu = [
    {
      menu1 : "리뷰보기",
      menu2 : "시공사례",
      menu3 : "커뮤니티",
      menu4 : "3D인테리어 소개"
    },
    {
      menu1 : "견적내기",
      menu2 : "시공사례",
      menu3 : "커뮤니티",
      menu4 : "3D인테리어 소개"
    },
    {
      menu1 : "입찰하기",
      menu2 : "업체소개",
      menu3 : "커뮤니티",
      menu4 : "3D인테리어 소개"
    }
  ]

  const menuLink = [
    {
      menu1 : "#",
      menu2 : "#",
      menu3 : "/comunity/1",
      menu4 : "#"
    },
    {
      menu1 : "/estimating",
      menu2 : "#",
      menu3 : "/comunity/1",
      menu4 : "#"
    },
    {
      menu1 : "/bidding",
      menu2 : "#",
      menu3 : "/comunity/1",
      menu4 : "#"
    }
  ]

  return (
    <html lang="en">
      <body> 
        <div className='navbar'>
          <Link style={{marginLeft : "20px"}} href={"#"}><img className='logoImg' src='/logoImg.png'/><img className='logoText' src='/logoText.png'/></Link>
          <ul>
            <li><Link href={menuLink[menuType].menu1}>{menu[menuType].menu1}</Link></li>
            <li><Link href={menuLink[menuType].menu2}>{menu[menuType].menu2}</Link></li>
            <li><Link href={menuLink[menuType].menu3}>{menu[menuType].menu3}</Link></li>
            <li><Link href={menuLink[menuType].menu4}>{menu[menuType].menu4}</Link></li>
            { 
              session 
                ? <li><Link href={`/chat/${session.user._id}`}>채팅</Link> <span>{session.user.name}</span><LogOutBtn/></li>
                : <li><LoginBtn/><RegisterBtn style={{color: "#71A894"}}/></li>
            }
          </ul>
        </div>
        {children}
      </body>
    </html>
  )
}
